name: Generate API

runs:
    using: "composite"
    steps:
      - name: Install proto buf
        run: sudo apt install -y protobuf-compiler
        shell: bash
      - name: Install Go protobuf plugins
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        shell: bash
      - name: Install Go gRPC plugins
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        shell: bash

      - name: Initialize Git Submodules
        run: git submodule init
        shell: bash
      - name: Update Git Submodules
        run: git submodule update
        shell: bash

      - name: Generate api
        run: make
        shell: bash
